/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.slides.aula01.exercicios.ex04;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author andre
 */
public class Exercicio04 extends javax.swing.JFrame implements ActionListener {

    static double numero1 = 0, numero2 = 0, resultado = 0;
    static String sinal = "";

    /**
     * Creates new form Exercicio04
     */
    public Exercicio04() {
        initComponents();
        btn1.addActionListener(this);
        btn2.addActionListener(this);
        btn3.addActionListener(this);
        btn4.addActionListener(this);
        btn5.addActionListener(this);
        btn6.addActionListener(this);
        btn7.addActionListener(this);
        btn8.addActionListener(this);
        btn9.addActionListener(this);
        btn0.addActionListener(this);
        btnSoma.addActionListener(this);
        btnSubtrai.addActionListener(this);
        btnMultiplica.addActionListener(this);
        btnDivide.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResultados = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        pnlConta = new javax.swing.JPanel();
        lblConta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnSoma = new javax.swing.JButton();
        btnSubtrai = new javax.swing.JButton();
        btnMultiplica = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        pnlResultados.setBackground(new java.awt.Color(255, 204, 204));
        pnlResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlResultados.add(lblResultado);

        pnlConta.setBackground(new java.awt.Color(255, 204, 204));
        pnlConta.add(lblConta);

        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        btn1.setText("1");
        btn1.setOpaque(false);
        jPanel2.add(btn1);

        btn2.setText("2");
        jPanel2.add(btn2);

        btn3.setText("3");
        jPanel2.add(btn3);

        btn4.setText("4");
        jPanel2.add(btn4);

        btn5.setText("5");
        jPanel2.add(btn5);

        btn6.setText("6");
        jPanel2.add(btn6);

        btn7.setText("7");
        jPanel2.add(btn7);

        btn8.setText("8");
        jPanel2.add(btn8);

        btn9.setText("9");
        jPanel2.add(btn9);

        btn0.setText("0");
        jPanel2.add(btn0);

        btnSoma.setText("+");
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSoma);

        btnSubtrai.setText("-");
        btnSubtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtraiActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubtrai);

        btnMultiplica.setText("*");
        btnMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicaActionPerformed(evt);
            }
        });
        jPanel2.add(btnMultiplica);

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        jPanel2.add(btnDivide);

        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        jPanel2.add(btnIgual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResultados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        if (lblConta.getText().length() == 10) {
            return;
        }
        limpar();
        System.out.println("sinal: " + sinal);
        System.out.println("var: " + numero1);
        System.out.println("label: " + lblConta.getText());

        JButton btn = (JButton) e.getSource();

        if (btn == btnSoma || btn == btnSubtrai || btn == btnMultiplica || btn == btnDivide) {
            sinal = btn.getText();
        } else {
            String numero = btn.getText();
            lblConta.setText(lblConta.getText() + numero);
        }
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        lblConta.setText("");
        lblResultado.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        numero1 = Double.parseDouble(lblConta.getText());
        lblResultado.setText(lblConta.getText() + " + ");
        lblConta.setText("");
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        numero2 = Double.parseDouble(lblConta.getText());
        System.out.println(sinal);
        switch (sinal) {
            case "+":
                resultado = numero1 + numero2;
                break;
            case "-":
                resultado = numero1 - numero2;
                break;
            case "*":
                resultado = numero1 * numero2;
                break;
            case "/":
                resultado = numero1 / numero2;
                break;
            default:
                break;
        }
        lblResultado.setText(Double.toString(numero1) + " " + sinal + " " + Double.toString(numero2) + " = ");
        lblConta.setText(Double.toString(resultado));
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnSubtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtraiActionPerformed
        numero1 = Double.parseDouble(lblConta.getText());
        lblResultado.setText(lblConta.getText() + " - ");
        lblConta.setText("");
    }//GEN-LAST:event_btnSubtraiActionPerformed

    private void btnMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicaActionPerformed
        numero1 = Double.parseDouble(lblConta.getText());
        lblResultado.setText(lblConta.getText() + " * ");
        lblConta.setText("");
    }//GEN-LAST:event_btnMultiplicaActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        numero1 = Double.parseDouble(lblConta.getText());
        lblResultado.setText(lblConta.getText() + " / ");
        lblConta.setText("");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void limpar() {
        if (resultado != 0) {
//            numero1 = Double.parseDouble(lblConta.getText());
            lblResultado.setText("");
            resultado = 0;
//            lblConta.setText("");
//            sinal = "";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplica;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtrai;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel pnlConta;
    private javax.swing.JPanel pnlResultados;
    // End of variables declaration//GEN-END:variables
}
